@startuml
skinparam actorStyle awesome
"Администратор" as Admin
"Авторизованный пользователь" as User
(Авторизация) as (authorize)
(Просмотр личного кабинета) as (check_own_profile)
(Редактировать личный кабинет) as (update_own_profile)
(Поиск) as (search)
(Прослушивание музыки) as (listen_to_music)
(Фильтр) as (filter)
(Музыкальный контент) as (music_content)
(Список пользователей) as (list_users)
(Плеер) as (music_player)
(Управление плеером) as (music_player_management)
(Добавление) as (add_content)
(Удаление) as (delete_content)
(Профиль пользователя) as userProfile
(Плейлисты) as playlist
(Альбомы) as album
(Треки) as tracks
(Исполнители) as artist
(Редактирование своей музыкальной библиотеки) as editLibrary


:Неавторизованный пользователь: --> (authorize)
:User:-|>:Неавторизованный пользователь:
:Admin:-|>:User:

:User: --> (check_own_profile)
:User: --> (listen_to_music)
:User: --> (search)
:Admin: --> (add_content)
:Admin: --> (delete_content)
(search)..|>(filter):include
(filter)<|...(music_content):extend
(filter)<|..(list_users):extend
(listen_to_music)..|>(music_player):include
(music_player)<|..(music_player_management):extend
(check_own_profile)<|..(update_own_profile):extend
(music_content)..|>(playlist):include
(music_content)..|>(album):include
(music_content)..|>(tracks):include
(music_content)..|>(artist):include
:User:-->(editLibrary)
(delete_content)...|>(music_content):include
(add_content)..|>(music_content):include
(list_users)..|>(userProfile):include
(delete_content)...|>(list_users):include
@enduml