@startuml
|#AntiqueWhite|Авторизованный пользователь|
start
:Заполнение формы;
|#AntiqueWhite|UI|
:Проверка данных;
if() then (Данные введены неверно)
:Информация об ошибке;
else (Данные введены верно)
:Отправка данных на редактирование;
|#AntiqueWhite|Backend|
:Запрос на наличие пользователей с такими данными;
|#AntiqueWhite|База данных|
:Выборка;
|#AntiqueWhite|Backend|
:Ответ от БД;
if() then ([Данные уникуальны] Запрос на изменение)
|#AntiqueWhite|База данных|
:Изменение;
|#AntiqueWhite|Backend|
:Ответ от БД;
else (Данные не уникальны)
:Информация об ошибке;
endif
|#AntiqueWhite|UI|
endif
|#AntiqueWhite|Авторизованный пользователь|
if() then (Изменение данных)
:           Отображение страницы
зарегистрированного пользователя;
stop
else(Ошибка)
:Информация об ошибке;
stop

@enduml
