@startuml

|#AntiqueWhite|Неавторизированный пользователь|
start
:Заполнение формы;
|#AntiqueWhite|UI|
:Проверка данных;
if() then (Данные введены верно)
:Запрос на пользователя;
|#AntiqueWhite|База данных|
:Проверка существования пользователя;
|#AntiqueWhite|UI|
:Ответ от БД;
else (Данные введены неверно)
:Информация об ошибке;
endif
|#AntiqueWhite|Неавторизированный пользователь|
if() then (Авторизация)
:           Отображение страницы
зарегистрированного пользователя;
stop
else(Ошибка)
:Информация об ошибке;
stop
@enduml
