@startuml
|#AntiqueWhite|Неавторизированный пользователь|
start
:Окно авторизации;
|#AntiqueWhite|Пользователь|
if() then (Нет аккаунта)
:Регистрация;
:Авторизация;
else (Ввод данных пользователя)
:Авторизация;
endif
:Главная страница;
switch()
case(Переход на страницу поиска)
:Поиск музыки;
case(Переход в плеер)
:Прослушивание музыки;
case(Переход в личный кабинет)
    :Личный кабинет;
        switch()
        case()
            :Изменение настроек профиля;
        case()
            :Просмотр избранного;
        case()
            if(Роль:Администратор) then (Нет)
            |#AntiqueWhite|Администратор|
            else (Да)
            :Добавление контента;
            endif
        endswitch
endswitch
|#AntiqueWhite|Пользователь|
:Выйти из профиля;
|#AntiqueWhite|Неавторизированный пользователь|
:Окно авторизации;
stop
@enduml
