@startuml
|#AntiqueWhite|Авторизованный пользователь|
start
:Заполнение формы;
|#AntiqueWhite|UI|
:Запрос на музыку;
|#AntiqueWhite|База данных|
:Проверка существования музыки;
|#AntiqueWhite|UI|
:Ответ от БД;
|#AntiqueWhite|Авторизованный пользователь|
if() then (Найдено)
:Вывод найденной музыки;
stop
else(Не найдено)
:"По вашему запросу ничего не найдено";
stop
@enduml