@startuml

|#AntiqueWhite|Неавторизированный пользователь|
start
:Окно авторизации;
|#AntiqueWhite|Пользователь|
if() then (Нет аккаунта)
:Регистрация;
:Авторизация;
else (Ввод данных пользователя)
:Авторизация;
endif
:Главная страница;
switch()
case()
case(1)
:Личный кабинет;
    switch()
    case()
      :Изменение настроек;
    case()
      :Просмотр статистики;
    case()
      :Просмотр избранного;
    case()
      :Просмотр уведомлений о новой музыке
               избранных исполнителей;
    case()
    if(Роль:Модератор) then (Нет)

    |#AntiqueWhite|Администратор|
    else (Да)
    :Добавление контента;
    endif
    endswitch

:Прослушивание музыки с помощью плеера;
|#AntiqueWhite|Пользователь|

|#AntiqueWhite|Неавторизированный пользователь|



@enduml
