@startuml
autonumber

participant "Пользователь" as Пользователь
participant "Система" as Система
database "База данных" as database

autonumber
activate Система
activate Пользователь
Пользователь -> Система: Данные авторизации
deactivate Пользователь


Система -> Система:Проверка
activate Система

deactivate Система

Система -->Пользователь:[некорректный ввод] ошибка
activate Пользователь
deactivate Пользователь
Система -> database:[корректные данные] запрос на пользователя
deactivate Система
activate database

database -> database:Проверка
database-->Система: Ответ
deactivate database

activate Система

Система -->Пользователь:[пользователь не найден] ошибка
activate Пользователь
deactivate Пользователь
Система -->Пользователь:[пользователь найден] авторизация
deactivate Система
activate Пользователь
deactivate Пользователь
@enduml