@startuml

|#AntiqueWhite|Неавторизированный пользователь|
start
:Заполнение формы;
|#AntiqueWhite|UI|
:Проверка данных;
if() then (Данные введены неверно)
:Информация об ошибке;
else (Данные введены верно)
:Отправка данных на регистрацию;
|#AntiqueWhite|Backend|
:Запрос на наличие пользователей с такими данными;
|#AntiqueWhite|База данных|
:Проверка существования пользователя;
|#AntiqueWhite|Backend|
:Ответ от БД;
if() then ([Данные уникуальны] Запрос на добавление)
|#AntiqueWhite|База данных|
:Добавление записи о пользователе;
|#AntiqueWhite|Backend|
:Ответ от БД;
else (Данные не уникальны)
:Информация об ошибке;
endif
|#AntiqueWhite|UI|
endif
|#AntiqueWhite|Неавторизированный пользователь|
if() then (Регистрация)
:           Отображение страницы
зарегистрированного пользователя;
stop
else(Ошибка)
:Информация об ошибке;
stop

@enduml
