@startuml
autonumber

actor "Пользователь" as user
participant "UI" as ui
participant "Backend" as backend
database "База данных" as database

activate ui
activate user
user->ui:Ввод измененных данных
deactivate user
ui->ui:Проверка введенных данных
activate ui
deactivate ui
ui-->user:[некорректные данные] ошибка
activate user
deactivate user
ui->backend:[корректные данные] отправка данных на редактирование
deactivate ui
activate backend
backend->database:Запрос на пользователей с введенными данными
deactivate backend
activate database
database->database:Проверка
activate database
deactivate database
database-->backend:Ответ
deactivate database
activate backend
backend-->ui:[пользователь с такими данными существуют] ошибка
activate ui
ui-->user:Это значение уже было использовано
deactivate ui
activate user
backend->database:Запрос на изменение данных
deactivate backend
deactivate user
activate database
database->database:Изменение данных
activate database
deactivate database
database-->backend:Ответ
deactivate database
activate backend
backend-->ui:Возврат новых пользовательских данных
deactivate backend
activate ui
ui-->user:Отображение страницы зарегистрированного пользователя
deactivate ui
activate user
@enduml